</section>
	<hr>		
	<center><h4>LISTA DE PRODUCTOS</h4></center>
	<div id="contienecarrito" >
			<div id="carrito" style="background:rgb(200,200,255);color:black; border-radius:10px;">
			Carrito
			</div>
			
			<a href='php/destruir.php'><button class='btn btn-warning'>
				<span class='glyphicon glyphicon-remove'></span>
				Vaciar carrito</button></a>
			<a href='confirmar.php'><button class='btn btn-success'>
				<span class='glyphicon glyphicon-ok'></span>
				Confirmar compra</button></a>
	</div>
			<footer>
				<hr>
				<center><h6><span class="glyphicon glyphicon-copyright-mark"></span> Desarrollado por Stark Systems. 
					<img src='img/logo.png' width='40'/></h6>
					
				</center>
			</footer>
		</div>
	</body>
</html>
